site_name: Marin Documentation
site_description: Documentation for the Marin project
site_url: https://marin.community

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotation
    - content.code.copy
    - navigation.footer
  language: en
  palette:
      - scheme: slate
        toggle:
          icon: material/weather-sunny
          name: Switch to light mode
        primary: black
        accent: white
      - scheme: default
        toggle:
          icon: material/weather-night
          name: Switch to dark mode
        primary: black
        accent: white
  icon:
      repo: fontawesome/brands/git-alt
      edit: material/pencil
      view: material/eye
  logo: static/logo.png
  favicon: static/favicon.ico


repo_url: https://github.com/marin-community/marin
repo_name: marin-community/marin

# Include extra JS to setup Read the Docs addons integrations
extra_javascript:
  - javascript/readthedocs.js

extra_css:
  - css/mkdocstrings.css
  - css/custom.css
  - css/friendly.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/marin-community/marin
    - icon: fontawesome/brands/discord
      link: https://discord.gg/DhbGDq3jv4

watch:
  - docs/
  - lib/marin/src/


nav:
  - Home: index.md
  - Tutorials:
    - Installation: tutorials/installation.md
    - First Experiment: tutorials/first-experiment.md
    - Setting up a Local GPU Environment: tutorials/local-gpu.md
    - Prepare a Storage Bucket: tutorials/storage-bucket.md
    - Setting up a TPU Cluster: tutorials/tpu-cluster-setup.md
    - Executor 101: tutorials/executor-101.md
    - Data Browser: tutorials/data-browser.md
    - Using Data Shop: tutorials/datashop.md
    - Training an LM: tutorials/train-an-lm.md
    - Submitting a Speedrun: tutorials/submitting-speedrun.md
    - Filtering Data: tutorials/filtering-data.md
    - Running an Annealing Experiment: tutorials/annealing-experiment.md
    - Co-Developing with Marin and Levanter: tutorials/co-develop.md
    - Adding an Optimizer for Speedrun: tutorials/add-optimizer.md
  - Explanations:
    - The Language Modeling Pipeline: explanations/lm-pipeline.md
    - Datashop: explanations/datashop.md
    - Evaluation: explanations/evaluation.md
    - Experiments: explanations/experiments.md
    - Executor: explanations/executor.md
    - Guidelines: explanations/guidelines.md
  - Experiments:
    - Report Index: reports/index.md
    - Auto-Generated Summary: reports/summary.md
    - Marin 8B Retro: reports/marin-8b-retro.md
    - Marin 32B Retro: reports/marin-32b-retro.md
    - Markdownified Datasets: reports/markdownified-datasets.md
  - Developer Guide:
    - Contributing: dev-guide/contributing.md
    - Deployment: dev-guide/deployment.md
    - Tutorial Guidelines: dev-guide/tutorial-guidelines.md
    - Internal Guidelines: dev-guide/guidelines-internal.md
    - Building Docs: dev-guide/building-docs.md
    - Snapshot Tests: dev-guide/snapshot-tests.md
  - Technical Reference:
    - Specifying Hardware Resources: references/resource-config.md
    - Executor API: references/executor-api.md
    - Default Steps: references/default-steps.md
    - Training Configuration: references/train-config.md

markdown_extensions:
  - markdown.extensions.footnotes
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.arithmatex
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.highlight:
     anchor_linenums: true
  - admonition
  - footnotes
  - toc:
      permalink: true

plugins:
  - search:
      lang: en
      separator: '[\s\-\.]+'
      # min_search_length: 2
      # prebuild_index: true
      # # indexing: 'full'
      # properties:
      #     - title
      #     - tags
      #     - content
      #     - sections
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [".", "lib/marin/src"]
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://jax.readthedocs.io/en/latest/objects.inv
            - https://haliax.readthedocs.io/en/latest/objects.inv
            - https://levanter.readthedocs.io/en/latest/objects.inv
            - https://docs.kidger.site/equinox/objects.inv
            - https://einops.rocks/objects.inv
          options:
            annotations_path: brief
            ignore_init_summary: true
            docstring_style: google
            show_source: false
            docstring_section_style: list
            heading_level: 4
            inherited_members: true
            merge_init_into_class: false
            load_external_modules: true
            show_signature_annotations: true
            show_root_heading: true
            show_root_full_path: false
            show_bases: true
            show_submodules: true
            filters: ["!^_"]
            show_if_no_docstring: true
            show_symbol_type_heading: false
            show_symbol_type_toc: false
            show_category_heading: true
            members_order: source
            separate_signature: true
            line_length: 60
            signature_crossrefs: true

  - include-markdown
