apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: iris-controller
subjects:
  - kind: ServiceAccount
    name: iris-controller
    namespace: iris
roleRef:
  kind: ClusterRole
  name: iris-controller
  apiGroup: rbac.authorization.k8s.io
