name: Levanter - Run entry tests

on:
  push:
    branches:
      - main
    paths:
      - lib/levanter/**
      - uv.lock
      - .github/workflows/levanter-run_entry_tests.yaml
  pull_request:
    paths:
      - lib/levanter/**
      - uv.lock
      - .github/workflows/levanter-run_entry_tests.yaml

jobs:
  entry_tests:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    defaults:
      run:
        working-directory: lib/levanter

    steps:
      - uses: actions/checkout@v4
      - name: Install uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.20"
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          working-directory: lib/levanter
      - name: Set up Python
        run: uv python install
      - name: Install dependencies
        run: uv sync --package levanter --dev --frozen
      - name: Test with pytest
        run: |
          PYTHONPATH=tests:src:. uv run --package levanter --frozen pytest tests -m "entry" --durations=20
