name: Zephyr - Tests
on:
  push:
    branches:
      - main
    paths:
      - lib/zephyr/**
      - uv.lock
      - .github/workflows/zephyr-unit-tests.yaml
  pull_request:
    branches:
      - main
    paths:
      - lib/zephyr/**
      - uv.lock
      - .github/workflows/zephyr-unit-tests.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cpu-unit-test:
    runs-on: [cpu-ci]
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          version: "0.7.20"
          enable-cache: true

      - name: Install dependencies
        run: |
          uv pip install --upgrade pip
          uv sync --package zephyr --group test --frozen

      - name: Test with pytest
        run: |
          # important: don't cd into lib/zephyr so that ray uv integration doesn't freak out
          uv run --package zephyr --frozen pytest --durations=5 --tb=short -m 'not slow and not tpu_ci' -v lib/zephyr/tests/
